spring.application.name=backend

# Spring Boot ANSI Fix for JDK 23/24
spring.output.ansi.enabled=NEVER
server.port=8081

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/erp_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
erp.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
erp.app.jwtExpirationMs=86400000
