INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_SALES_EXECUTIVE');
INSERT IGNORE INTO roles(name) VALUES('ROLE_PURCHASE_MANAGER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_INVENTORY_MANAGER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ACCOUNTANT');
